POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpIiwiaWQiOiI1YjFmYTk2OTY2ZjEwNjU2NDA5ZTExNmUiLCJpYXQiOjE1Mjg4MTEyMjd9.u8nWggAopZKurKCQ-YKUnfQurdoGJDO6B4AhX0vhD3w

{
    "subject": "juuuu!",
    "content": "Asiasta ei ole epäilystäkään.",
    "userId": "5b1fa96966f10656409e116e"
}