POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlZpaXZpIiwiaWQiOiI1YmNkZDRjN2RlMjRlNzQ0NzhlOGU0NzIiLCJpYXQiOjE1NDAyMjA4NDd9.2KqRTyhfxFkXREp29yscmdu6c0hRsF836jSvZalmxF4

{
    "subject": "testaaa",
    "content": "jje.",
    "userId": "5b1fa96966f10656409e116e",
    "category": {
  "id": "5bd1cf48ea190f46ec867fea",
  "content": "toinenkategoria",
  "blogs": []
}
}