POST http://localhost:3001/api/comments
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpIiwiaWQiOiI1YjFmYTk2OTY2ZjEwNjU2NDA5ZTExNmUiLCJpYXQiOjE1MzEzODM1ODN9.xNIW9vYgTUBgbQoUYuAnN8WDKq1iF0NcWa7AdM86Hd8

{
    "content": "tämä toimii",
    "userId": "5b1fa96966f10656409e116e",
    "blogId": "5b291a229c8014258413b09c"
}